apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollouts-demo
spec:
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m

---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http
    nodePort: 31043
    protocol: TCP
    name: http
  selector:
    app: rollouts-demo

